---
name: ffpass

on: [push, pull_request_target]

jobs:
  test:
    name: Test
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: >
          python -m pip install --upgrade pip &&
          python -m pip install
          coveralls
          -r requirements.txt
          -r requirements-dev.txt

      - name: Test with pytest
        run: make test

      - name: Lint with flake8
        run: make lint

      - name: Submit coverage report / coveralls
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python -m coveralls --service=github
